### ISSUE TITLE
Implement rfcs/0001-restructure.go

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/go#15]
We've recently merged https://github.com/paketo-buildpacks/go/blob/master/rfcs/0001-restructure-go.md. Below is a set of steps we can take to implement this RFC.

- [x] Add a language-family test suite: https://github.com/paketo-buildpacks/go/pull/51
- [x] Rename `go-compiler` to `go-dist`: https://github.com/paketo-buildpacks/go-dist/pull/65 and https://github.com/paketo-buildpacks/go/pull/92
- [x] Create `go-build`: https://github.com/paketo-buildpacks/go/issues/93
- [x] Create new `dep-ensure` that runs `dep ensure` https://github.com/paketo-buildpacks/go/issues/97 and https://github.com/paketo-buildpacks/dep-ensure/pull/4
- [x] Rename `go-mod` to `go-mod-vendor`  https://github.com/paketo-buildpacks/go-mod/issues/64
- [x] Pull `go build` code out of `go-mod-vendor` and replace with `go-build` in the order group https://github.com/paketo-buildpacks/go-mod/issues/31 and https://github.com/paketo-buildpacks/go-mod/pull/71
- [x] Pull `go build` code out of `dep` and replace with `go-build` in the order group
- [x] Pull `dep ensure` code out of `dep` and replace with `dep-ensure` in the order group

**Comment by ryanmoran** [comment]
This is complete as of https://github.com/paketo-buildpacks/go/releases/tag/v0.0.11.
