### ISSUE TITLE
Implement Go RFC 0001: Remove `dep` and `dep-ensure`

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/go#622]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/go/0001-remove-dep.md)

## Summary
The dep and dep-ensure Buildpacks should be removed.

## Subtasks

- [x]  Add deprecation warnings
  - [x] https://github.com/paketo-buildpacks/dep/pull/313
  - [x] https://github.com/paketo-buildpacks/dep-ensure/pull/252
- [x] Release language family with deprecation warnings included

[ After 30 days ]
- [x] Remove unsupported buildpacks from language family order groups
- [x] Archive unsupported buildpack repos

**Comment by ForestEckhardt** [comment]
30 days from Release August 18th, 2022

**Comment by ForestEckhardt** [comment]
Everything has been removed checked on this list so I am going to close out this issue
