### ISSUE TITLE
Support Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/go#624]
## Describe the Enhancement

Ultimately, we want to be able to build Golang apps on top of the Paketo Jammy stacks. Currently, builds fail because buildpacks like `go-dist` don't have the Jammy stack listed in their supported stacks.

## Possible Solution

- Update `buildpack.toml` and dependencies to add `io.buildpacks.stacks.jammy` and `io.buildpacks.stacks.jammy.tiny` as compatible stacks
- (If necessary) Recompile installed dependencies to work on Jammy 
- Add some integration tests that test the buildpack against Jammy stacks

## Motivation

Part of https://github.com/paketo-buildpacks/builder-jammy-base/issues/1

## Subtasks

- [x] - https://github.com/paketo-buildpacks/dep-server/pull/161
- [x] - https://github.com/paketo-buildpacks/dep-server/pull/185
- [x] - https://github.com/paketo-buildpacks/go-dist/pull/402
- [ ] https://github.com/paketo-buildpacks/go-dist/pull/415
- [x] - https://github.com/paketo-buildpacks/dep/pull/310
- [x] - https://github.com/paketo-buildpacks/dep/pull/307
- [x] - https://github.com/paketo-buildpacks/dep-ensure/pull/250
